---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-{{ .Release.Name }}-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"

spec:
  rules:
  - host: team20.api-dealer.ru
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend-{{ .Release.Name }}
            port:
              number: 3000