---
apiVersion: v1
kind: Service
metadata:
  name: backend-{{ .Release.Name }}-service
  labels:
    app: backend
spec:
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    app: backend
    release: {{ .Release.Name }}
