source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.0.1"

gem "rails", github: "rails/rails", branch: "main"
gem "sprockets-rails"
gem "pg", "~> 1.1"
gem "puma", "~> 5.0"
gem "tzinfo-data"

gem 'grape'
gem 'grape-entity'
gem 'grape_logging'
gem 'grape-swagger'
gem 'grape-swagger-entity'
gem 'grape-swagger-rails'

gem 'will_paginate'

gem 'faraday'

gem 'devise'
gem 'devise-jwt'
gem 'rack-cors', '~> 1.1', '>= 1.1.1'

gem 'bunny'

gem 'seedbank'
gem 'faker', require: false

group :development, :test do
  gem 'rubocop'
  gem 'byebug'
end

group :test do
  gem 'database_cleaner-active_record'
  gem 'factory_bot_rails'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'simplecov', require: false
  gem 'webmock'
end
