export const FIELDS = {
  name: 'name',
  surname: 'surname',
  patronomic: 'patronomic',
  lastname: 'lastname',
  password: 'password',
  repeatPassword: 'repeatPassword',
  birthday: 'birthday',
  phone: 'phone',
  email: 'email',
  gender: 'gender',
  education: 'education',
  status: 'status',
  workName: 'work_name',
  position: 'position',
  experience: 'experience',
  positionType: 'position_type',
  officePhone: 'office_phone',
  familyStatus: 'family_status',
  proxyName: 'proxy_name',
  proxySurname: 'proxy_surname',
  proxyPatronomic: 'proxy_patronomic',
  proxyBirthday: 'proxy_birthday',
  proxyPhone: 'proxy_phone',
  proxyEmail: 'proxy_email',
  passportNumber: 'passport_number',
  passportDate: 'passport_date',
  passportCode: 'passport_code',
  passportIssuedBy: 'passport_issued_by',
  birthPlace: 'birth_place',
  registrationAddress: 'registration_address',
  registrationIndex: 'registration_index',
  registrationDate: 'registration_date',
  registrationStatus: 'registration_status',
  agree: 'agree',
  registrationMatches: 'registration_matches',
  salary: 'salary',
  children: 'children',
  dependents: 'dependents',
  requiredPayments: 'required_payments',
  repayment: 'repayment',
}

export const STRING_FIELDS = [
  FIELDS.name,
  FIELDS.surname,
  FIELDS.patronomic,
  FIELDS.birthday,
  FIELDS.phone,
  FIELDS.email,
  FIELDS.gender,
  FIELDS.education,
  FIELDS.status,
  FIELDS.workName,
  FIELDS.position,
  FIELDS.experience,
  FIELDS.positionType,
  FIELDS.officePhone,
  FIELDS.familyStatus,
  FIELDS.proxyName,
  FIELDS.proxySurname,
  FIELDS.proxyPatronomic,
  FIELDS.proxyBirthday,
  FIELDS.proxyPhone,
  FIELDS.proxyEmail,
  FIELDS.passportNumber,
  FIELDS.passportDate,
  FIELDS.passportCode,
  FIELDS.passportIssuedBy,
  FIELDS.birthPlace,
  FIELDS.registrationAddress,
  FIELDS.registrationIndex,
  FIELDS.registrationDate,
  FIELDS.registrationStatus,
]

export const BOOL_FIELDS = [FIELDS.agree, FIELDS.registrationMatches]

export const NUMBER_FIELDS = [
  FIELDS.salary,
  FIELDS.children,
  FIELDS.dependents,
  FIELDS.requiredPayments,
  FIELDS.repayment,
]

export const REGISTER_FIELDS = [
  FIELDS.name,
  FIELDS.surname,
  FIELDS.lastname,
  FIELDS.email,
  FIELDS.password,
  FIELDS.repeatPassword,
]

export const PERSONAL_FIELDS = [
  FIELDS.name,
  FIELDS.surname,
  FIELDS.patronomic,
  FIELDS.phone,
  FIELDS.email,
  FIELDS.gender,
  FIELDS.birthday,
]
